/*
Deployment script for lodovico_dump

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "lodovico_dump"
:setvar DefaultFilePrefix "lodovico_dump"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS OFF,
                ANSI_PADDING OFF,
                ANSI_WARNINGS OFF,
                ARITHABORT OFF,
                CONCAT_NULL_YIELDS_NULL OFF,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER OFF,
                ANSI_NULL_DEFAULT OFF,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                DATE_CORRELATION_OPTIMIZATION OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = AUTO, OPERATION_MODE = READ_WRITE, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET TEMPORAL_HISTORY_RETENTION ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating Table [dbo].[faq_responses]...';


GO
CREATE TABLE [dbo].[faq_responses] (
    [id]                 BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]       BIGINT             NOT NULL,
    [created_at]         DATETIMEOFFSET (3) NOT NULL,
    [question]           NVARCHAR (MAX)     NOT NULL,
    [answer]             NVARCHAR (MAX)     NOT NULL,
    [is_common_question] BIT                NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Index [dbo].[faq_responses].[faq_responses_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [faq_responses_candidate_id_idx]
    ON [dbo].[faq_responses]([candidate_id] ASC);


GO
PRINT N'Creating Index [dbo].[faq_responses].[faq_responses_common_idx]...';


GO
CREATE NONCLUSTERED INDEX [faq_responses_common_idx]
    ON [dbo].[faq_responses]([candidate_id] ASC, [is_common_question] ASC);


GO
PRINT N'Creating Table [dbo].[certifications]...';


GO
CREATE TABLE [dbo].[certifications] (
    [id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]     BIGINT             NOT NULL,
    [name]             NVARCHAR (1024)    NOT NULL,
    [issuer]           NVARCHAR (512)     NULL,
    [issue_date]       DATE               NULL,
    [expiration_date]  DATE               NULL,
    [credential_id]    NVARCHAR (256)     NULL,
    [verification_url] NVARCHAR (2048)    NULL,
    [notes]            NVARCHAR (MAX)     NULL,
    [display_order]    INT                NULL,
    [created_at]       DATETIMEOFFSET (3) NOT NULL,
    [updated_at]       DATETIMEOFFSET (3) NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Index [dbo].[certifications].[certifications_display_order_idx]...';


GO
CREATE NONCLUSTERED INDEX [certifications_display_order_idx]
    ON [dbo].[certifications]([candidate_id] ASC, [display_order] ASC);


GO
PRINT N'Creating Index [dbo].[certifications].[certifications_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [certifications_candidate_id_idx]
    ON [dbo].[certifications]([candidate_id] ASC);


GO
PRINT N'Creating Table [dbo].[values_culture]...';


GO
CREATE TABLE [dbo].[values_culture] (
    [id]                           BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]                 BIGINT             NOT NULL,
    [created_at]                   DATETIMEOFFSET (3) NOT NULL,
    [must_haves]                   NVARCHAR (MAX)     NOT NULL,
    [dealbreakers]                 NVARCHAR (MAX)     NOT NULL,
    [management_style_preferences] NVARCHAR (MAX)     NULL,
    [team_size_preferences]        NVARCHAR (MAX)     NULL,
    [how_handle_conflict]          NVARCHAR (MAX)     NULL,
    [how_handle_ambiguity]         NVARCHAR (MAX)     NULL,
    [how_handle_failure]           NVARCHAR (MAX)     NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Index [dbo].[values_culture].[values_culture_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [values_culture_candidate_id_idx]
    ON [dbo].[values_culture]([candidate_id] ASC);


GO
PRINT N'Creating Table [dbo].[gaps_weaknesses]...';


GO
CREATE TABLE [dbo].[gaps_weaknesses] (
    [id]                   BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]         BIGINT             NOT NULL,
    [created_at]           DATETIMEOFFSET (3) NOT NULL,
    [gap_type]             NVARCHAR (64)      NOT NULL,
    [description]          NVARCHAR (450)     NOT NULL,
    [why_its_a_gap]        NVARCHAR (MAX)     NULL,
    [interest_in_learning] BIT                NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [gaps_weaknesses_candidate_description_unique] UNIQUE NONCLUSTERED ([candidate_id] ASC, [description] ASC)
);


GO
PRINT N'Creating Index [dbo].[gaps_weaknesses].[gaps_weaknesses_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [gaps_weaknesses_candidate_id_idx]
    ON [dbo].[gaps_weaknesses]([candidate_id] ASC);


GO
PRINT N'Creating Table [dbo].[experiences]...';


GO
CREATE TABLE [dbo].[experiences] (
    [id]                   BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]         BIGINT             NOT NULL,
    [created_at]           DATETIMEOFFSET (3) NOT NULL,
    [company_name]         NVARCHAR (450)     NOT NULL,
    [title]                NVARCHAR (MAX)     NULL,
    [title_progression]    NVARCHAR (MAX)     NULL,
    [start_date]           DATE               NULL,
    [end_date]             DATE               NULL,
    [is_current]           BIT                NOT NULL,
    [bullet_points]        NVARCHAR (MAX)     NULL,
    [why_joined]           NVARCHAR (MAX)     NULL,
    [why_left]             NVARCHAR (MAX)     NULL,
    [actual_contributions] NVARCHAR (MAX)     NULL,
    [proudest_achievement] NVARCHAR (MAX)     NULL,
    [would_do_differently] NVARCHAR (MAX)     NULL,
    [challenges_faced]     NVARCHAR (MAX)     NULL,
    [lessons_learned]      NVARCHAR (MAX)     NULL,
    [manager_would_say]    NVARCHAR (MAX)     NULL,
    [reports_would_say]    NVARCHAR (MAX)     NULL,
    [quantified_impact]    NVARCHAR (MAX)     NULL,
    [display_order]        INT                NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [experiences_candidate_company_unique] UNIQUE NONCLUSTERED ([candidate_id] ASC, [company_name] ASC, [start_date] ASC)
);


GO
PRINT N'Creating Index [dbo].[experiences].[experiences_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [experiences_candidate_id_idx]
    ON [dbo].[experiences]([candidate_id] ASC);


GO
PRINT N'Creating Index [dbo].[experiences].[experiences_candidate_order_idx]...';


GO
CREATE NONCLUSTERED INDEX [experiences_candidate_order_idx]
    ON [dbo].[experiences]([candidate_id] ASC, [display_order] ASC, [start_date] ASC);


GO
PRINT N'Creating Table [dbo].[skill_equivalence]...';


GO
CREATE TABLE [dbo].[skill_equivalence] (
    [id]              BIGINT             IDENTITY (1, 1) NOT NULL,
    [skill_name]      NVARCHAR (512)     NOT NULL,
    [equivalent_name] NVARCHAR (512)     NOT NULL,
    [created_at]      DATETIMEOFFSET (3) NOT NULL,
    [notes]           NVARCHAR (MAX)     NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Index [dbo].[skill_equivalence].[skill_equivalence_unique]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [skill_equivalence_unique]
    ON [dbo].[skill_equivalence]([skill_name] ASC, [equivalent_name] ASC);


GO
PRINT N'Creating Table [dbo].[ai_instructions]...';


GO
CREATE TABLE [dbo].[ai_instructions] (
    [id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]     BIGINT             NOT NULL,
    [created_at]       DATETIMEOFFSET (3) NOT NULL,
    [instruction_type] NVARCHAR (64)      NOT NULL,
    [instruction]      NVARCHAR (MAX)     NOT NULL,
    [priority]         INT                NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Index [dbo].[ai_instructions].[ai_instructions_priority_idx]...';


GO
CREATE NONCLUSTERED INDEX [ai_instructions_priority_idx]
    ON [dbo].[ai_instructions]([candidate_id] ASC, [instruction_type] ASC, [priority] ASC);


GO
PRINT N'Creating Index [dbo].[ai_instructions].[ai_instructions_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [ai_instructions_candidate_id_idx]
    ON [dbo].[ai_instructions]([candidate_id] ASC);


GO
PRINT N'Creating Table [dbo].[skills]...';


GO
CREATE TABLE [dbo].[skills] (
    [id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]     BIGINT             NOT NULL,
    [created_at]       DATETIMEOFFSET (3) NOT NULL,
    [skill_name]       NVARCHAR (1024)    NOT NULL,
    [category]         NVARCHAR (64)      NOT NULL,
    [self_rating]      INT                NULL,
    [evidence]         NVARCHAR (MAX)     NULL,
    [honest_notes]     NVARCHAR (MAX)     NULL,
    [years_experience] DECIMAL (4, 1)     NULL,
    [last_used]        DATE               NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [skills_candidate_skill_name_unique] UNIQUE NONCLUSTERED ([candidate_id] ASC, [skill_name] ASC)
);


GO
PRINT N'Creating Index [dbo].[skills].[skills_candidate_category_idx]...';


GO
CREATE NONCLUSTERED INDEX [skills_candidate_category_idx]
    ON [dbo].[skills]([candidate_id] ASC, [category] ASC);


GO
PRINT N'Creating Index [dbo].[skills].[skills_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [skills_candidate_id_idx]
    ON [dbo].[skills]([candidate_id] ASC);


GO
PRINT N'Creating Table [dbo].[candidate_profile]...';


GO
CREATE TABLE [dbo].[candidate_profile] (
    [id]                    BIGINT             IDENTITY (1, 1) NOT NULL,
    [created_at]            DATETIMEOFFSET (3) NOT NULL,
    [updated_at]            DATETIMEOFFSET (3) NOT NULL,
    [name]                  NVARCHAR (MAX)     NOT NULL,
    [email]                 NVARCHAR (512)     NOT NULL,
    [title]                 NVARCHAR (MAX)     NULL,
    [target_titles]         NVARCHAR (MAX)     NULL,
    [target_company_stages] NVARCHAR (MAX)     NULL,
    [elevator_pitch]        NVARCHAR (MAX)     NULL,
    [career_narrative]      NVARCHAR (MAX)     NULL,
    [looking_for]           NVARCHAR (MAX)     NULL,
    [not_looking_for]       NVARCHAR (MAX)     NULL,
    [management_style]      NVARCHAR (MAX)     NULL,
    [work_style]            NVARCHAR (MAX)     NULL,
    [salary_min]            DECIMAL (12, 2)    NULL,
    [salary_max]            DECIMAL (12, 2)    NULL,
    [availability_status]   NVARCHAR (128)     NULL,
    [availability_date]     DATE               NULL,
    [location]              NVARCHAR (MAX)     NULL,
    [remote_preference]     NVARCHAR (128)     NULL,
    [github_url]            NVARCHAR (2048)    NULL,
    [linkedin_url]          NVARCHAR (2048)    NULL,
    [twitter_url]           NVARCHAR (2048)    NULL,
    [email_lc]              AS                 (lower([email])) PERSISTED,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Index [dbo].[candidate_profile].[candidate_profile_email_uidx]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [candidate_profile_email_uidx]
    ON [dbo].[candidate_profile]([email] ASC);


GO
PRINT N'Creating Table [dbo].[education]...';


GO
CREATE TABLE [dbo].[education] (
    [id]             BIGINT             IDENTITY (1, 1) NOT NULL,
    [candidate_id]   BIGINT             NOT NULL,
    [created_at]     DATETIMEOFFSET (3) NOT NULL,
    [institution]    NVARCHAR (450)     NULL,
    [degree]         NVARCHAR (256)     NULL,
    [field_of_study] NVARCHAR (256)     NULL,
    [start_date]     DATE               NULL,
    [end_date]       DATE               NULL,
    [is_current]     BIT                NOT NULL,
    [grade]          NVARCHAR (64)      NULL,
    [notes]          NVARCHAR (MAX)     NULL,
    [display_order]  INT                NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [education_candidate_institution_unique] UNIQUE NONCLUSTERED ([candidate_id] ASC, [institution] ASC, [degree] ASC, [start_date] ASC)
);


GO
PRINT N'Creating Index [dbo].[education].[education_candidate_id_idx]...';


GO
CREATE NONCLUSTERED INDEX [education_candidate_id_idx]
    ON [dbo].[education]([candidate_id] ASC);


GO
PRINT N'Creating Table [dbo].[ai_response_cache]...';


GO
CREATE TABLE [dbo].[ai_response_cache] (
    [hash]            NVARCHAR (128)     NOT NULL,
    [question]        NVARCHAR (MAX)     NOT NULL,
    [model]           NVARCHAR (256)     NOT NULL,
    [response]        NVARCHAR (MAX)     NOT NULL,
    [cache_hit_count] INT                NOT NULL,
    [last_accessed]   DATETIMEOFFSET (3) NOT NULL,
    [updated_at]      DATETIMEOFFSET (3) NOT NULL,
    [invalidated_at]  DATETIMEOFFSET (3) NULL,
    [is_cached]       BIT                NOT NULL,
    PRIMARY KEY CLUSTERED ([hash] ASC)
);


GO
PRINT N'Creating Index [dbo].[ai_response_cache].[ai_response_cache_last_accessed_idx]...';


GO
CREATE NONCLUSTERED INDEX [ai_response_cache_last_accessed_idx]
    ON [dbo].[ai_response_cache]([last_accessed] ASC);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[faq_responses]...';


GO
ALTER TABLE [dbo].[faq_responses]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[faq_responses]...';


GO
ALTER TABLE [dbo].[faq_responses]
    ADD DEFAULT ((0)) FOR [is_common_question];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[certifications]...';


GO
ALTER TABLE [dbo].[certifications]
    ADD DEFAULT ((0)) FOR [display_order];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[certifications]...';


GO
ALTER TABLE [dbo].[certifications]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[certifications]...';


GO
ALTER TABLE [dbo].[certifications]
    ADD DEFAULT (sysdatetimeoffset()) FOR [updated_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[values_culture]...';


GO
ALTER TABLE [dbo].[values_culture]
    ADD DEFAULT (N'[]') FOR [dealbreakers];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[values_culture]...';


GO
ALTER TABLE [dbo].[values_culture]
    ADD DEFAULT (N'[]') FOR [must_haves];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[values_culture]...';


GO
ALTER TABLE [dbo].[values_culture]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[gaps_weaknesses]...';


GO
ALTER TABLE [dbo].[gaps_weaknesses]
    ADD DEFAULT ((0)) FOR [interest_in_learning];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[gaps_weaknesses]...';


GO
ALTER TABLE [dbo].[gaps_weaknesses]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[experiences]...';


GO
ALTER TABLE [dbo].[experiences]
    ADD DEFAULT (N'[]') FOR [bullet_points];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[experiences]...';


GO
ALTER TABLE [dbo].[experiences]
    ADD DEFAULT ((0)) FOR [is_current];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[experiences]...';


GO
ALTER TABLE [dbo].[experiences]
    ADD DEFAULT ((0)) FOR [display_order];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[experiences]...';


GO
ALTER TABLE [dbo].[experiences]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[skill_equivalence]...';


GO
ALTER TABLE [dbo].[skill_equivalence]
    ADD DEFAULT (sysutcdatetime()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ai_instructions]...';


GO
ALTER TABLE [dbo].[ai_instructions]
    ADD DEFAULT ((100)) FOR [priority];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ai_instructions]...';


GO
ALTER TABLE [dbo].[ai_instructions]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[skills]...';


GO
ALTER TABLE [dbo].[skills]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[candidate_profile]...';


GO
ALTER TABLE [dbo].[candidate_profile]
    ADD DEFAULT (N'[]') FOR [target_titles];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[candidate_profile]...';


GO
ALTER TABLE [dbo].[candidate_profile]
    ADD DEFAULT (N'[]') FOR [target_company_stages];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[candidate_profile]...';


GO
ALTER TABLE [dbo].[candidate_profile]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[candidate_profile]...';


GO
ALTER TABLE [dbo].[candidate_profile]
    ADD DEFAULT (sysdatetimeoffset()) FOR [updated_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[education]...';


GO
ALTER TABLE [dbo].[education]
    ADD DEFAULT (sysdatetimeoffset()) FOR [created_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[education]...';


GO
ALTER TABLE [dbo].[education]
    ADD DEFAULT ((0)) FOR [is_current];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[education]...';


GO
ALTER TABLE [dbo].[education]
    ADD DEFAULT ((0)) FOR [display_order];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ai_response_cache]...';


GO
ALTER TABLE [dbo].[ai_response_cache]
    ADD DEFAULT ((0)) FOR [is_cached];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ai_response_cache]...';


GO
ALTER TABLE [dbo].[ai_response_cache]
    ADD DEFAULT (sysdatetimeoffset()) FOR [updated_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ai_response_cache]...';


GO
ALTER TABLE [dbo].[ai_response_cache]
    ADD DEFAULT ((0)) FOR [cache_hit_count];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ai_response_cache]...';


GO
ALTER TABLE [dbo].[ai_response_cache]
    ADD DEFAULT (sysdatetimeoffset()) FOR [last_accessed];


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[faq_responses]...';


GO
ALTER TABLE [dbo].[faq_responses]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[certifications]...';


GO
ALTER TABLE [dbo].[certifications]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[values_culture]...';


GO
ALTER TABLE [dbo].[values_culture]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[gaps_weaknesses]...';


GO
ALTER TABLE [dbo].[gaps_weaknesses]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[experiences]...';


GO
ALTER TABLE [dbo].[experiences]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[ai_instructions]...';


GO
ALTER TABLE [dbo].[ai_instructions]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[skills]...';


GO
ALTER TABLE [dbo].[skills]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[education]...';


GO
ALTER TABLE [dbo].[education]
    ADD FOREIGN KEY ([candidate_id]) REFERENCES [dbo].[candidate_profile] ([id]) ON DELETE CASCADE;


GO
PRINT N'Creating Check Constraint [dbo].[gaps_weaknesses_gap_type_chk]...';


GO
ALTER TABLE [dbo].[gaps_weaknesses]
    ADD CONSTRAINT [gaps_weaknesses_gap_type_chk] CHECK ([gap_type]='role_type' OR [gap_type]='environment' OR [gap_type]='experience' OR [gap_type]='skill');


GO
PRINT N'Creating Check Constraint [dbo].[experiences_date_range_chk]...';


GO
ALTER TABLE [dbo].[experiences]
    ADD CONSTRAINT [experiences_date_range_chk] CHECK ([end_date] IS NULL OR [start_date] IS NULL OR [end_date]>=[start_date]);


GO
PRINT N'Creating Check Constraint [dbo].[ai_instructions_instruction_type_chk]...';


GO
ALTER TABLE [dbo].[ai_instructions]
    ADD CONSTRAINT [ai_instructions_instruction_type_chk] CHECK ([instruction_type]='boundaries' OR [instruction_type]='tone' OR [instruction_type]='honesty');


GO
PRINT N'Creating Check Constraint [dbo].[skills_category_chk]...';


GO
ALTER TABLE [dbo].[skills]
    ADD CONSTRAINT [skills_category_chk] CHECK ([category]='gap' OR [category]='moderate' OR [category]='strong');


GO
PRINT N'Creating Check Constraint [dbo].[skills_years_experience_chk]...';


GO
ALTER TABLE [dbo].[skills]
    ADD CONSTRAINT [skills_years_experience_chk] CHECK ([years_experience] IS NULL OR [years_experience]>=(0));


GO
PRINT N'Creating Check Constraint [dbo].[skills_self_rating_chk]...';


GO
ALTER TABLE [dbo].[skills]
    ADD CONSTRAINT [skills_self_rating_chk] CHECK ([self_rating] IS NULL OR [self_rating]>=(1) AND [self_rating]<=(5));


GO
PRINT N'Creating Check Constraint [dbo].[candidate_profile_salary_range_chk]...';


GO
ALTER TABLE [dbo].[candidate_profile]
    ADD CONSTRAINT [candidate_profile_salary_range_chk] CHECK ([salary_min] IS NULL OR [salary_max] IS NULL OR [salary_min]<=[salary_max]);


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
ALTER DATABASE [$(DatabaseName)]
    SET ENCRYPTION ON 
    WITH ROLLBACK IMMEDIATE;


GO
