declare const Typed: any;
declare const Waypoint: any;
declare const Isotope: any;
declare const AOS: any;
declare const GLightbox: any;
declare const Swiper: any;
declare const PureCounter: any;
declare const React: any;
declare const ReactDOM: any;
