name: PR CI CHECKS

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  make-check:
    name: CI CHECKS
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: INSTALL DEPENDENCIES
        run: make install

      - name: CHECKS
        run: make check
